server:
  port: 9000
  servlet:
    context-path: /
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    username: demo
    password: 111111
    url: jdbc:mysql://127.0.0.1:3306/db_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  #thymeleaf
  thymeleaf:
    cache: false

mybatis:
  mapperLocations: classpath*:/**/*Mapper.xml

logging:
  level:
    root: debug
